=== faucetsdn/udmi/schema/config_pointset.json
{
  "title": "Pointset Config",
  "description": "[Pointset Config Documentation](../docs/messages/pointset.md#config)",
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "timestamp": {
      "description": "RFC 3339 timestamp the configuration was generated",
      "type": "string",
      "format": "date-time",
      "examples": ["2019-01-17T14:02:29.364Z"]
    },
    "version": {
      "description": "Version of the UDMI schema",
      "type": "string"
    },
    "state_etag": {
      "description": "The `state_etag` of the last _state_ message sent by the device. [Writeback documentation](../docs/specs/sequences/writeback.md)",
      "type": "string",
      "maxLength": 32
    },
    "set_value_expiry": {
      "description": "An expiry for the the device to revert to baseline (no set value). [Writeback documentation](../docs/specs/sequences/writeback.md)",
      "type": "string",
      "format": "date-time"
    },
    "sample_limit_sec": {
      "description": "Minimum time between sample updates for the device (including complete and COV updates). Updates more frequent than this should be coalesced into one update.",
      "type": "integer",
      "minimum": 0,
      "maximum": 86400
    },
    "sample_rate_sec": {
      "description": "Maximum time between samples for the device to send out a complete update. It can send out updates more frequently than this. Default to 600.",
      "type": "integer",
      "minimum": 1,
      "maximum": 86400
    },
    "points": {
      "description": "The points defined in this dictionary is the authoritative source indicating the representative points for the device (in both `telemetry` and `state` messages). [Pointset doumentation](../docs/messages/pointset.md)",
      "additionalProperties": false,
      "existingJavaType": "java.util.HashMap<String, PointPointsetConfig>",
      "patternProperties": {
        "^[a-z][a-z0-9]*(_[a-z0-9]+)*$": {
          "$ref": "file:config_pointset_point.json#"
        }
      }
    }
  }
}

=== faucetsdn/udmi/tests/schemas/state_pointset/example.json
{
  "version": "1.4.2",
  "timestamp": "2018-08-26T21:39:29.364Z",
  "state_etag": "2a8b718",
  "points": {
    "room_temperature": {
      "value_state": "applied"
    },
    "hallway_temperature": {
      "value_state": "overridden"
    },
    "hallway_lights": {
      "value_state": "updating"
    },
    "entryway_lock": {
      "value_state": "failure",
      "status": {
        "message": "Failure to confirm point",
        "category": "pointset.point.failure",
        "timestamp": "2018-08-26T21:39:28.364Z",
        "level": 600
      }
    },
    "scale_sensor": {
      "value_state": "invalid",
      "status": {
        "message": "Point is not writable",
        "category": "pointset.point.invalid",
        "timestamp": "2018-08-26T21:39:28.364Z",
        "level": 600
      }
    },
    "rocket_motor": {
    }
  }
}
